version: '3.8'

services:
  api:
    build: .
    container_name: regioes_criticas_api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: uvicorn api_fastapi_regioes_criticas:app --host 0.0.0.0 --port 8000

  frontend:
    image: node:18
    container_name: regioes_criticas_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

  testes:
    image: python:3.11
    container_name: regioes_criticas_testes
    depends_on:
      - api
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "pip install pytest requests && pytest testes_api_modelo.py"
